$(document).ready(function(){
	$(".content").hide();
	$("#content-profile").show();
	$(".menu").mouseover(function(){
		$(this).addClass("hover");
	});
	$(".menu").mouseout(function(){
		$(this).removeClass("hover");
	});
	$("#click-profile").click(function(){
		$(".menu").removeClass("click");
		$(this).addClass("click");
		$(".content").hide();
		$("#content-profile").show();
	});
	$("#click-experience").click(function(){
		$(".menu").removeClass("click");
		$(this).addClass("click");
		$(".content").hide();
		$("#content-experience").show();
	});
	$("#click-education").click(function(){
		$(".menu").removeClass("click");
		$(this).addClass("click");
		$(".content").hide();
		$("#content-education").show();
	});
	$("#click-certifications").click(function(){
		$(".menu").removeClass("click");
		$(this).addClass("click");
		$(".content").hide();
		$("#content-certifications").show();
	});
	$("#click-volunteer").click(function(){
		$(".menu").removeClass("click");
		$(this).addClass("click");
		$(".content").hide();
		$("#content-volunteer").show();
	});
});

